"""Initial

Revision ID: fc8dab748a3d
Revises: 
Create Date: 2024-02-21 19:51:38.509706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8dab748a3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('path_in_storage', sa.String(length=255), nullable=False),
                    sa.Column('filename', sa.String(length=255), nullable=False),
                    sa.Column('size', sa.Integer(), nullable=False),
                    sa.Column('file_type', sa.String(length=100), nullable=True),
                    sa.Column('short_name', sa.String(length=24), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('path_in_storage'),
                    sa.UniqueConstraint('short_name')
                    )
    op.create_index('idx_file_path', 'files', ['path_in_storage'], unique=False)
    op.create_index('idx_file_short_name', 'files', ['short_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_file_short_name', table_name='files')
    op.drop_index('idx_file_path', table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
